import { TournamentScenario } from '../types/tournament';

export const TOURNAMENT_SCENARIOS: TournamentScenario[] = [
  {
    id: 'lucky_cue_8ball_winner_stays',
    name: '🎱 Lucky Cue 8-Ball Scotch Doubles (Winner Stays)',
    description: '6 Tables at Lucky Cue (Moorpark, CA). Max 10 Cap. Winner retains table and racks up for the next queued challenger in the pipeline.',
    gameType: '8_ball',
    format: 'winner_stays_queue',
    maxSkillCap: 10,
    defaultTablesCount: 6,
    startingChipsPolicy: 'handicap_matrix',
    isWinnerStays: true,
  },
  {
    id: 'lucky_cue_9ball_winner_stays',
    name: '🟡 Lucky Cue 9-Ball Scotch Doubles (Winner Stays)',
    description: '6 Tables at Lucky Cue (Moorpark, CA). Fast-paced 9-ball rules. Winner stays on table, loser loses 1 chip and re-enters pipeline.',
    gameType: '9_ball',
    format: 'scotch_doubles_9ball',
    maxSkillCap: 10,
    defaultTablesCount: 6,
    startingChipsPolicy: 'handicap_matrix',
    isWinnerStays: true,
  },
  {
    id: 'lucky_cue_8ball_max12',
    name: '🔥 Lucky Cue Open Max 12 Scotch Doubles (8-Ball)',
    description: 'Higher handicap ceiling (Max 12) for master/advanced pairings. 6 Tables, handicap chip allocation matrix.',
    gameType: '8_ball',
    format: 'scotch_doubles_8ball',
    maxSkillCap: 12,
    defaultTablesCount: 6,
    startingChipsPolicy: 'handicap_matrix',
    isWinnerStays: true,
  },
  {
    id: 'lucky_cue_9ball_max12',
    name: '⚡ Lucky Cue Open Max 12 Scotch Doubles (9-Ball)',
    description: 'High-octane 9-ball tournament with Max 12 cap across 6 tables at Lucky Cue Moorpark.',
    gameType: '9_ball',
    format: 'scotch_doubles_9ball',
    maxSkillCap: 12,
    defaultTablesCount: 6,
    startingChipsPolicy: 'handicap_matrix',
    isWinnerStays: true,
  },
  {
    id: 'lucky_cue_singles_8ball',
    name: '👤 Lucky Cue 8-Ball Singles Chip Survivor',
    description: '1 vs 1 solo player chip survivor format across 6 tables. APA 8-ball Equalizer handicap starting chips.',
    gameType: '8_ball',
    format: 'singles_8ball',
    maxSkillCap: 9,
    defaultTablesCount: 6,
    startingChipsPolicy: 'handicap_matrix',
    isWinnerStays: true,
  },
  {
    id: 'lucky_cue_singles_9ball',
    name: '🎯 Lucky Cue 9-Ball Singles Chip Survivor',
    description: '1 vs 1 solo player 9-ball chip survivor format across 6 tables. Fast rotation and queue pipeline.',
    gameType: '9_ball',
    format: 'singles_9ball',
    maxSkillCap: 9,
    defaultTablesCount: 6,
    startingChipsPolicy: 'handicap_matrix',
    isWinnerStays: true,
  },
  {
    id: 'lucky_cue_equal_chips_5',
    name: '⚖️ Lucky Cue Equal Chips (5 Chips Each — Sudden Death)',
    description: 'All pairings start with exactly 5 virtual chips regardless of handicap. High tension, rapid eliminations across 6 tables.',
    gameType: '8_ball',
    format: 'winner_stays_queue',
    maxSkillCap: 10,
    defaultTablesCount: 6,
    startingChipsPolicy: 'equal',
    isWinnerStays: true,
  },
];
